### ISSUE TITLE
6U Kubesat disappearing

### ISSUE THREAD

**Issue by Faucon-Noir** [AstroWell/Luciole#7]
Place 6U Kubesat
Right click on it
Put your mouse on the details menu
Kraken take control of 6U Kubesat's textures
fortunately, the kraken returns its textures to the 6U kubesat when the mouse exits the detailed menu
![image](https://user-images.githubusercontent.com/76254888/117284113-c92d0480-ae66-11eb-9071-ea6eb7bd90c6.png)
![image](https://user-images.githubusercontent.com/76254888/117284138-d0541280-ae66-11eb-9ef6-85c733aa58d9.png)

As the mouse does not appear on the screen, I put it on the texture change button to see its position
My game is modded with this
I'm playing KSP 1.11.1
[mod.txt](https://github.com/AstroWell/Luciole/files/6433765/mod.txt)

**Comment by AstroWell** [comment]
Those part use the classic Squad variant system, nothing spécial. so i suppose that could be a conflict with Textures Unlimited or something like that. Could be also a KSP issue tbh, 1.11.1 was still really buggy 1.11.2 is still btw.

I'm going to invetigate on my side, but i really don't see what could make an issue.

**Comment by AstroWell** [comment]
btw... je vois que ton jeu est en français, tu peux donc m'écrire en français si tu le souhaite

**Comment by Faucon-Noir** [comment]
Oui désolé, j'ai l'habitude de travailler avec des devs anglophone ^^'
Je vais tester avec une copie vanilla 1.11.1 et Luciole pour voir ce que ça donne
J'espère que c'est effectivement un conflit dû à un mod (moins problématique que natif)

**Comment by Faucon-Noir** [comment]
Je viens de vérifier, il n'y a plus ce problème en vanilla 1.11.1 + Luciole
Et avec mes autres mods, ça n'affecte que le 6U, aucune autre pièce n'est affectée
